version: '3.2'
services:
  faucet:
    container_name: faucet
    domainname: gnxi.lan
    hostname: faucet
    dns_search: gnxi.lan
    build:
      context: .
      dockerfile: docker/faucet/Dockerfile
    ports:
      - target: 6653
        published: 6653
        protocol: tcp
        mode: host
      - target: 9302
        published: 9302
        protocol: tcp
        mode: host
    networks:
       ovsgnxi_default:
          aliases:
            - faucet.gnxi.lan
  target:
    container_name: target
    domainname: gnxi.lan
    hostname: target
    dns_search: gnxi.lan
    privileged: true
    cap_add:
      - ALL
    build:
      context: .
      dockerfile: docker/target/Dockerfile
    volumes:
      - /lib/modules:/lib/modules
    ports:
      - target: 6640
        published: 6640
        protocol: tcp
        mode: host
      - target: 18080
        published: 18080
        protocol: tcp
        mode: host
      - target: 32123
        published: 32123
        protocol: tcp
        mode: host
    tty: true
    networks:
       ovsgnxi_default:
          aliases:
            - target.gnxi.lan
    depends_on:
      - faucet
  client:
    container_name: client
    domainname: gnxi.lan
    hostname: client
    dns_search: gnxi.lan
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    tty: true
    networks:
       ovsgnxi_default:
          aliases:
            - client.gnxi.lan
networks:
  ovsgnxi_default: